[build]
  command = "npm run build"
  publish = "dist"

[context.deploy-preview]
  command = "npm run build-preview"

[context.deploy-preview.environment]
  HUGO_VERSION = "1.0"

[context.production.environment]
  HUGO_VERSION = "1.0"
